services:
  fp-nvhpc-cc86-linux-amd64:
    image: krishnaa42342/fp:nvhpc_cc86
    container_name: fp-nvhpc-cc86
    network_mode: "host"
    volumes:
      - "./:/scratch"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
              driver: nvidia
    environment:
      DISPLAY: $DISPLAY
    stdin_open: true
    tty: true
  fp-nvhpc-cc70-linux-ppc64le:
    image: krishnaa42342/fp:nvhpc_cc70
    container_name: fp-nvhpc-cc70
    network_mode: "host"
    volumes:
      - "./:/scratch"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
              driver: nvidia
    environment:
      DISPLAY: $DISPLAY
    stdin_open: true
    tty: true
  fp-intelhpc-linux-amd64:
    image: krishnaa42342/fp:intelhpc
    container_name: fp-intelhpc
    network_mode: "host"
    volumes:
      - "./:/scratch"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
              driver: nvidia
    environment:
      DISPLAY: $DISPLAY
    stdin_open: true
    tty: true
  fp-mpich-linux-amd64:
    image: krishnaa42342/fp:mpich
    container_name: fp-mpich
    network_mode: "host"
    volumes:
      - "./:/scratch"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
              driver: nvidia
    environment:
      DISPLAY: $DISPLAY
    stdin_open: true
    tty: true
  fp-openmpi-linux-amd64:
    image: krishnaa42342/fp:openmpi
    container_name: fp-openmpi
    network_mode: "host"
    volumes:
      - "./:/scratch"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
              driver: nvidia
    environment:
      DISPLAY: $DISPLAY
    stdin_open: true
    tty: true