services:
  fp-nvhpc-linux-amd64-cc86:
    image: krishnaa42342/fp:nvhpc_cc86
    build:
      context: ./
      dockerfile: ./Dockerfile_nvhpc
      args:
        PLATFORM: Linux-x86_64
        CUDA_CC: 86
      platforms:
        - linux/amd64
  fp-nvhpc-linux-amd64-cc80:
    image: krishnaa42342/fp:nvhpc_cc80
    build:
      context: ./
      dockerfile: ./Dockerfile_nvhpc
      args:
        PLATFORM: Linux-x86_64
        CUDA_CC: 80
      platforms:
        - linux/amd64
  fp-nvhpc-linux-ppc64le-cc70:
    image: krishnaa42342/fp:nvhpc
    build:
      context: ./
      dockerfile: ./Dockerfile_nvhpc_cc70
      args:
        PLATFORM: Linux-ppc64le
        CUDA_CC: 70
      platforms:
        - linux/ppc64le
  fp-intelhpc-linux-amd64:
    image: krishnaa42342/fp:intelhpc
    build:
      context: ./
      dockerfile: ./Dockerfile_intelhpc
      args:
        PLATFORM: Linux-x86_64
      platforms:
        - linux/amd64
  fp-mpich-linux-amd64:
    image: krishnaa42342/fp:mpich
    build:
      context: ./
      dockerfile: ./Dockerfile_mpich
      args:
        PLATFORM: Linux-x86_64
      platforms:
        - linux/amd64
  fp-openmpi-linux-amd64:
    image: krishnaa42342/fp:openmpi
    build:
      context: ./
      dockerfile: ./Dockerfile_openmpi
      args:
        PLATFORM: Linux-x86_64
      platforms:
        - linux/amd64
      