services:
  fp-gcc-arm64:
    image: krishnaa42342/fp:gcc-arm64
    build:
      context: ./
      dockerfile: ./Dockerfile_gcc_arm64
      platforms:
        - linux/arm64
  fp-base-arm64:
    image: krishnaa42342/fp:base-arm64
    build:
      context: ./
      dockerfile: ./Dockerfile_base_arm64
      platforms:
        - linux/arm64
  fp-intelhpc-amd64:
    image: krishnaa42342/fp:intelhpc-amd64
    build:
      context: ./
      dockerfile: ./Dockerfile_intelhpc_amd64
      platforms:
        - linux/amd64
  fp-nvhpc-amd64:
    image: krishnaa42342/fp:nvhpc-cc86-amd64
    build:
      context: ./
      dockerfile: ./Dockerfile_nvhpc_amd64
      args:
        CUDA_CC: 86
      platforms:
        - linux/amd64
      