FROM ubuntu:22.04 

ENV SHELL=/bin/bash
ENV BASH_ENV=~/.bashrc
ENV DEBIAN_FRONTEND=noninteractive
ENV PS1='\[\e[0;32m\]\u@\h:\[\e[0;34m\]\w\[\e[0m\]\$ '
ENV PATH=/usr/local/bin:$PATH
ENV CPATH=/usr/local/include:$CPATH
ENV LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
ENV OMPI_ALLOW_RUN_AS_ROOT=1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
ENV CONDA_AUTO_ACTIVATE_BASE=false
ENV CONDA_ROOT=/root/miniconda
ENV CONDA_SET=$CONDA_ROOT/etc/profile.d/conda.sh
ENV SCRATCH=/usr/local
SHELL ["bash", "-c"]

RUN apt update -y \
&& apt install -y build-essential \
    software-properties-common \
    gfortran \
    python3 python3-pip \
    wget curl vim git gh \
    ninja-build meson autoconf libtool pkg-config \
    libssl-dev \
    libgtk-4-dev libgirepository1.0-dev libcairo2-dev gir1.2-glib-2.0 \
    qt6-base-dev qt6-tools-dev qt6-tools-dev-tools \
    libgl1-mesa-dev libglu1-mesa-dev libgl1-mesa-glx \
    openssh-client openssh-server \
&& ln -sf /usr/bin/python3 /usr/bin/python

# clang
RUN wget https://apt.llvm.org/llvm.sh \
&& chmod +x ./llvm.sh \
&& ./llvm.sh all  \
&& rm -rf ./llvm.sh 

# # cmake
# RUN wget -O cmake.tar.gz https://github.com/Kitware/CMake/archive/refs/tags/v4.2.3.tar.gz \
# && tar -xzvf cmake.tar.gz && mv CMake-* cmake \
# && cd cmake \
# && CC=gcc CXX=g++ FC=gfortran ./bootstrap --prefix=$SCRATCH \
# && make -j8 && make install \
# && cd .. \
# && rm -rf cmake*

# boost
RUN wget -O boost.tar.gz https://archives.boost.io/release/1.90.0/source/boost_1_90_0.tar.gz \
&& tar -xzvf boost.tar.gz && rm -rf boost.tar.gz && mv boost* boost \
&& cd boost \
&& ./bootstrap.sh --prefix=$SCRATCH \
&& ./b2 -j8 install --prefix=$SCRATCH \
&& cd .. \
&& rm -rf boost*

# miniconda, julia
RUN wget -O ./miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh \
&& chmod +x ./miniconda.sh \
&& bash ./miniconda.sh -b -p $CONDA_ROOT \
&& rm -rf ./miniconda.sh \
&& echo '' >> ~/.bashrc \
&& echo 'if [ -f $CONDA_ROOT/etc/profile.d/conda.sh ]; then' >> ~/.bashrc \
&& echo '    . $CONDA_ROOT/etc/profile.d/conda.sh' >> ~/.bashrc \
&& echo 'fi' >> ~/.bashrc \
&& source $CONDA_SET \
&& conda activate base \
&& conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main \
&& conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r \
&& conda install -c conda-forge cmake \
&& conda deactivate \
# julia
&& wget -O julia.tar.gz https://julialang-s3.julialang.org/bin/linux/aarch64/1.10/julia-1.10.10-linux-aarch64.tar.gz \
&& tar -xzvf julia.tar.gz && mv julia-* julia \
&& cp -r ./julia/* /usr/local/ \
&& rm -rf ./julia* \
&& julia -e 'using Pkg; Pkg.add("WannierIO")'

# mpich, mpi4py 
RUN wget -O mpich.tar.gz https://github.com/pmodels/mpich/releases/download/v5.0.0/mpich-5.0.0.tar.gz \
&& tar -xzvf ./mpich.tar.gz \
&& mv mpich-* mpich && cd mpich \
&& autoreconf -i \
&& CC=gcc CXX=g++ FC=gfortran ./configure --prefix=$SCRATCH \
&& make -j8 && make install \
&& cd ../ \
&& rm -rf ./mpich* \
&& CC=mpicc MPICC=mpicc pip install --no-binary=mpi4py mpi4py 

# zlib
RUN wget -O zlib.tar.gz https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz \
&& tar -xzvf ./zlib.tar.gz \
&& mv zlib-* zlib && cd zlib \
&& CC=gcc CXX=g++ FC=gfortran ./configure --prefix=$SCRATCH \
&& make -j8 && make install \
&& cd ../ \
&& rm -rf ./zlib*

# hdf5
RUN wget -O hdf5.tar.gz https://github.com/HDFGroup/hdf5/archive/refs/tags/2.0.0.tar.gz \
&& tar -xf hdf5.tar.gz \
&& mv hdf5-* hdf5 && cd hdf5 \
&& mkdir -p build \
&& source $CONDA_SET && conda activate base \
&& CC=mpicc CXX=mpic++ FC=mpif90 cmake -S . -B build \
    -DCMAKE_INSTALL_PREFIX=$SCRATCH \
    -DBUILD_SHARED_LIBS=ON \
    -DHDF5_BUILD_FORTRAN=ON \
    -DHDF5_ENABLE_PARALLEL=ON \
    -DHDF5_ENABLE_ZLIB_SUPPORT=ON \
&& cmake --build build -j8 \
&& cmake --install build \
&& conda deactivate \
&& cd ../ \
&& rm -rf hdf5* 

# netcdf-c, netcdf-fortran, ncpy
RUN wget -O netcdf-c.tar.gz https://github.com/Unidata/netcdf-c/archive/refs/tags/v4.9.3.tar.gz \
&& tar -xzvf netcdf-c.tar.gz && mv netcdf-c-* netcdf-c \
&& cd netcdf-c \
&& autoreconf -i \
&& CC=mpicc CXX=mpic++ FC=mpif90 ./configure --prefix=$SCRATCH --disable-libxml2 --disable-dap --disable-nczarr \
&& make -j8 && make install \
&& cd .. \
&& rm -rf netcdf-c* \
# netcdf-fortran. 
&& wget -O netcdf-fortran.tar.gz  https://github.com/Unidata/netcdf-fortran/archive/refs/tags/v4.6.2.tar.gz \
&& tar -xzvf netcdf-fortran.tar.gz && mv netcdf-fortran-* netcdf-fortran \
&& cd netcdf-fortran \
&& autoreconf -i \
&& CC=mpicc CXX=mpic++ FC=mpif90 ./configure --prefix=$SCRATCH \
&& make -j8 && make install \
&& cd .. \
&& rm -rf netcdf-fortran* \
# netcdf-python. 
&& pip install netcdf4 

# openblas, scalapack
COPY ./SLmake.inc ./
RUN wget -O openblas.tar.gz https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.31/OpenBLAS-0.3.31.tar.gz \
&& tar -xf openblas.tar.gz \
&& mv OpenBLAS-* openblas && cd openblas \
&& CC=gcc CXX=g++ FC=gfortran make USE_OPENMP=1 COMMON_OPT="-fPIC" -j8 \
&& make install PREFIX=$SCRATCH \
&& cd ../ \
&& rm -rf openblas* \
&& wget -O scalapack.tar.gz https://github.com/Reference-ScaLAPACK/scalapack/archive/refs/tags/v2.2.2.tar.gz \
&& tar -xzvf ./scalapack.tar.gz \
&& mv scalapack-* scalapack && cd scalapack \
&& cp ../SLmake.inc ./ \
&& make lib \
&& cp ./libscalapack.a $SCRATCH/lib/libscalapack.a \
&& cd ../ \
&& rm -rf scalapack* SLmake.inc

# fftw
RUN wget -O fftw.tar.gz https://www.fftw.org/fftw-3.3.10.tar.gz \
&& tar -xzvf ./fftw.tar.gz \
&& mv fftw-* fftw && cd fftw \ 
&& CC=mpicc CXX=mpic++ FC=mpif90 ./configure --prefix=$SCRATCH FLAGS="-fPIC" FCFLAGS="-fPIC" --enable-shared --enable-openmp --enable-mpi \
&& make -j8 && make install \
&& CC=mpicc CXX=mpic++ FC=mpif90 ./configure --prefix=$SCRATCH FLAGS="-fPIC" FCFLAGS="-fPIC" --enable-shared --enable-threads --enable-mpi \
&& make -j8 && make install \
&& CC=mpicc CXX=mpic++ FC=mpif90 ./configure --prefix=$SCRATCH FLAGS="-fPIC" FCFLAGS="-fPIC" --enable-shared --enable-openmp --enable-mpi --enable-single \
&& make -j8 && make install \
&& CC=mpicc CXX=mpic++ FC=mpif90 ./configure --prefix=$SCRATCH FLAGS="-fPIC" FCFLAGS="-fPIC" --enable-shared --enable-threads --enable-mpi --enable-single \
&& make -j8 && make install \
&& cd ../ \
&& rm -rf fftw*

# elpa
RUN wget -O elpa.tar.gz https://gitlab.mpcdf.mpg.de/elpa/elpa/-/archive/new_release_2025.06.002/elpa-new_release_2025.06.002.tar.gz \
&& tar -xzvf ./elpa.tar.gz \
&& mv elpa-* elpa && cd elpa \
&& ./autogen.sh \
&& CC=mpicc CXX=mpic++ FC=mpif90 ./configure --prefix=$SCRATCH \
    --disable-shared \
    --disable-sse \
    --disable-sse-assembly \
    --disable-avx \
    --disable-avx2 \
    --disable-avx512 \
    CFLAGS="-O3 -fPIC" \
    LDFLAGS="-L$SCRATCH/lib" \
    LIBS="-lscalapack -lopenblas" \
&& make -j8 && make install \
&& cd ../ \
&& rm -rf elpa* \
&& ln -sf $SCRATCH/include/elpa-*/elpa $SCRATCH/include \
&& cp $SCRATCH/include/elpa-*/modules/* $SCRATCH/include 

# petsc, slepc
RUN wget -O petsc.tar.gz https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-3.24.2.tar.gz \
&& tar -xzvf ./petsc.tar.gz \
&& mv petsc-* petsc && cd petsc \
&& ./configure --with-cc=mpicc --with-cxx=mpic++ --prefix=$SCRATCH --with-scalar-type=complex --with-fc=0 \
&& make all -j8 && make install \
&& cd ../ \
&& rm -rf ./petsc* \
&& wget -O slepc.tar.gz https://slepc.upv.es/download/distrib/slepc-3.24.2.tar.gz \
&& tar -xzvf ./slepc.tar.gz \
&& mv slepc-* slepc && cd slepc \
&& ./configure --prefix=$SCRATCH \
&& make SLEPC_DIR=/slepc PETSC_DIR=$SCRATCH -j8 && make SLEPC_DIR=/slepc PETSC_DIR=$SCRATCH install \
&& cd ../ \
&& rm -rf ./slepc* \
&& CC=mpicc CXX=mpic++ PETSC_DIR=$SCRATCH SLEPC_DIR=$SCRATCH pip install --no-binary=petsc4py petsc4py \
&& CC=mpicc CXX=mpic++ PETSC_DIR=$SCRATCH SLEPC_DIR=$SCRATCH pip install --no-binary=slepc4py slepc4py 

# libxc
RUN wget -O libxc.tar.gz https://gitlab.com/libxc/libxc/-/archive/7.0.0/libxc-7.0.0.tar.gz \
&& tar -xzvf ./libxc.tar.gz \
&& mv libxc-* libxc && cd libxc \
&& apt install -y cmake \
&& autoreconf -i \
&& ./configure CFLAGS="-fPIC" --prefix=$SCRATCH \
&& make -j2 && make install \
# Fix for using newer cmake build.
# && sed -i 's/VERSION 3\.1/VERSION 3.5/' ./CMakeLists.txt \      
&& sed -i 's/nprocs = mp.cpu_count()/nprocs = 4  # Limited to prevent OOM/g' setup.py \
&& pip install --no-cache-dir . \
&& apt remove -y cmake \
&& cd ../ \
&& rm -rf ./libxc* 

# qe, perturbo, phonopy
COPY ./qe.tar.gz ./perturbo.tar.gz ./make.sys ./kmesh.pl ./
RUN cp ./kmesh.pl $SCRATCH/bin/kmesh.pl \
&& rm -rf ./kmesh.pl \
# qe
&& tar -xzvf ./qe.tar.gz \
&& mv q-e* qe && cd qe \
&& git config --global --add safe.directory '*'   \
&& CC=mpicc CXX=mpic++ FC=mpif90 ./configure \
    --prefix=$SCRATCH \
    --with-scalapack=yes \
    --with-elpa-include=$SCRATCH/include \
    --with-elpa-lib=$SCRATCH/lib/libelpa.a \
    --with-hdf5=yes \
    --with-hdf5-include=$SCRATCH/include \
    --with-hdf5-lib="-L$SCRATCH/lib -lhdf5_hl_fortran -lhdf5_hl -lhdf5_fortran -lhdf5 -lz -ldl -lm" \
    --with-libxc=yes \
    --with-libxc-prefix=$SCRATCH \
    --with-libxc-include=$SCRATCH/include \
&& make all -j8 && make epw -j8 \
# perturbo
&& cp ../perturbo.tar.gz ./ \
&& tar -xvf ./perturbo.tar.gz && cd perturbo \
&& cp ../../make.sys ./ \
&& make \
&& cd ../ \
&& make install \
&& cd ../ \
&& rm -rf ./qe* ./perturbo.tar.gz ./make.sys \
&& pip install perturbopy \
# phonopy
&& git clone https://github.com/phonopy/phonopy.git \
&& cd phonopy && git checkout master \
&& apt install -y cmake \
&& pip install nanobind scikit-build-core setuptools-scm setuptools packaging spglib \
&& pip install . --no-build-isolation -vvv \
&& apt remove cmake -y \
&& cd .. \
&& rm -rf phonopy 

# bgw 
COPY ./arch.mk ./bgw.tar.gz ./
RUN tar -xzvf ./bgw.tar.gz \
&& mv BerkeleyGW bgw && cd bgw \
&& cp ../arch.mk ./ \
&& make all-flavors -j8 \
&& make install INSTDIR=$SCRATCH \
&& cd ../ \
&& rm -rf ./bgw* ./arch.mk 

# abacus
RUN wget -O abacus.tar.gz https://github.com/deepmodeling/abacus-develop/archive/refs/tags/v3.9.0.24.tar.gz \
&& tar -xzvf ./abacus.tar.gz \
&& mv abacus-* abacus && cd abacus \
&& mkdir -p build \
&& source $CONDA_SET && conda activate base \
&& CXX=mpic++ cmake -S . -B build \
    -DCMAKE_INSTALL_PREFIX=$SCRATCH \
    -DUSE_ELPA=OFF \
&& cmake --build build -j8 \
&& cmake --install build \
&& conda deactivate \
&& cd ../ \
&& rm -rf ./abacus*

# siesta
RUN wget -O siesta.tar.gz https://gitlab.com/siesta-project/siesta/-/archive/5.4.2/siesta-5.4.2.tar.gz \
&& tar -xzvf ./siesta.tar.gz \
&& mv siesta-* siesta && cd siesta \
&& mkdir -p build \
&& source $CONDA_SET && conda activate base \
&& cmake -S . -B ./build -DCMAKE_INSTALL_PREFIX=$SCRATCH \
  -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
  -DCMAKE_PREFIX_PATH=$SCRATCH \
  -DLAPACK_LIBRARY=openblas \
  -DLAPACK_LIBRARY_DIR=$SCRATCH \
  -DSCALAPACK_LIBRARY_DIR=$SCRATCH \
  -DNetCDF_ROOT=$SCRATCH \
  -DSIESTA_WITH_MPI=ON \
  -DSIESTA_WITH_OPENMP=ON \
  -DSIESTA_WITH_FFTW=ON \
  -DSIESTA_WITH_LIBXC=ON \
  -DSIESTA_WITH_ELPA=ON \
  -DSIESTA_WITH_FLOOK=OFF \
  -DCMAKE_C_COMPILER=mpicc \
  -DCMAKE_CXX_COMPILER=mpic++ \
  -DCMAKE_Fortran_COMPILER=mpif90 \
&& cmake --build build -j8 \
&& cmake --install build \
&& conda deactivate \
&& cd ../ \
&& rm -rf ./siesta* 

# gpaw
COPY ./siteconfig_testing.py ./
RUN pip install --upgrade numpy \
&& pip install ase \
&& wget -O gpaw.tar.gz https://pypi.org/packages/source/g/gpaw/gpaw-25.7.0.tar.gz \
&& tar -xzvf ./gpaw.tar.gz \
&& mv gpaw-* gpaw && cd gpaw \
&& cp ../siteconfig_testing.py ./siteconfig.py \
&& CC=mpicc CXX=mpic++ FC=mpif90 pip install . --no-cache-dir \
&& yes | gpaw install-data /root/gpaw-data \
&& cd ../ \
&& rm -rf ./gpaw* ./siteconfig_testing.py

# lammps
RUN wget -O lammps.tar.gz https://github.com/lammps/lammps/archive/refs/tags/stable_22Jul2025_update3.tar.gz \
&& tar -xzvf lammps.tar.gz && mv lammps-* lammps \
&& cd lammps \
&& mkdir -p build \
&& source $CONDA_SET && conda activate base \
&& cmake -S ./cmake -B build \
    -DCMAKE_INSTALL_PREFIX=$SCRATCH \
    -DCMAKE_C_COMPILER=mpicc \
    -DCMAKE_CXX_COMPILER=mpic++ \
    -DCMAKE_Fortran_COMPILER=mpif90 \
&& cmake --build build -j8 \
&& cmake --install build \
&& conda deactivate \
&& cd ../ \
&& rm -rf lammps* 

# # xyce
# RUN apt install -y ngspice iverilog bison flex \
# && wget -O trilinos.tar.gz https://github.com/trilinos/Trilinos/archive/refs/tags/trilinos-release-17-0-0.tar.gz \
# && wget -O xyce.tar.gz https://github.com/Xyce/Xyce/archive/refs/tags/Release-7.10.0.tar.gz \
# && tar -xzvf ./xyce.tar.gz \
# && tar -xzvf ./trilinos.tar.gz \
# && mv Xyce-* xyce\
# && mv Trilinos-* trilinos  \
# && source $CONDA_SET & conda activate base \
# && cd trilinos \
# && mkdir -p build && cd ./build \
# && cmake -C ../../trilinos/trilinos-base.cmake ./ \
#     -DCMAKE_INSTALL_PREFIX=$SCRATCH \
#     -DTPL_ENABLE_AMD=OFF \
# && cmake --build . -j8 -t install \
# && cd ../../xyce && mkdir -p build \
# && cmake -S . -B build \
#     -DCMAKE_INSTALL_PREFIX=$SCRATCH \
#     -DTrilinos_ROOT=$SCRATCH \
# && cmake --build build -j8 \
# && cmake --install build \
# && cd ../ \
# && conda deactivate \
# && rm -rf ./xyce* trilinos*

# kicad, freecad, openscad
RUN apt update -y \
&& apt install -y \
    kicad \
    freecad \
    openscad 

# dolfinx, meep
RUN source $CONDA_SET && conda activate base \ 
&& conda create -n dolfinx -c conda-forge python=3.10 fenics-dolfinx pyvista \
&& conda create -n meep -c conda-forge python=3.10 pymeep=*=mpi_* \
&& conda deactivate 

# libtorch
RUN wget -O libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-2.10.0%2Bcpu.zip \
&& apt install -y unzip \
&& unzip ./libtorch.zip \
&& cp -r ./libtorch/* $SCRATCH/ \
&& rm -rf ./libtorch*

# Install packages
RUN pip install \
    numpy pandas scipy sympy matplotlib seaborn \
    scikit-learn joblib xgboost \
    torch torchvision torch_geometric transformers datasets accelerate evaluate diffusers e3nn \
    langchain langchain-huggingface \
    fastapi uvicorn \
    wxpython pymatgen mp_api pyvista[all] \
    gdspy meshio pyyaml jmespath lxml xmltodict python-benedict[all] \
&& pip install torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.8.0+cpu.html \
&& pip install --prefer-binary pyscf 
